"""Import-safe extension API bundled in the ``unified-cli`` distribution.

Importing this module performs no subprocess probes and does not import the ACP
or MCP optional dependencies.
"""

from .errors import (
    ConfigurationError,
    ExtensionError,
    LimitExceeded,
    OptionalDependencyError,
    ProcessFailed,
    ProviderReportedError,
    ProtocolError,
    TransportCancelled,
    TransportError,
    TransportTimeout,
    UnsupportedPlatformError,
)
from .normalization import (
    DoneEvent,
    ErrorEvent,
    EventNormalizer,
    FinalTextEvent,
    FrozenJsonMap,
    NormalizedEvent,
    PermissionDecision,
    PermissionRequestEvent,
    ReasoningSummaryEvent,
    SessionEvent,
    SessionRef,
    TextDeduplicator,
    TextDeltaEvent,
    ToolProgressEvent,
    ToolResultEvent,
    ToolStartEvent,
    UsageEvent,
    freeze_json,
)
from .permissions import PermissionPolicy, map_permission_decision
from .tools import McpCallableBridge, ToolCorrelator, require_mcp_sdk, validate_correlation_id
from .transports import (
    AcpProcessTransportV1,
    AcpSdkAdapter,
    CancellationToken,
    HttpSseClient,
    IsolatedEnvironment,
    JsonRpcId,
    JsonRpcProcessClient,
    JsonlProcess,
    SseEvent,
    TransportLimits,
    redact_diagnostics,
    require_acp_sdk,
)


__version__ = "0.5.4"

__all__ = [
    "__version__",
    "AcpProcessTransportV1",
    "AcpSdkAdapter",
    "CancellationToken",
    "ConfigurationError",
    "DoneEvent",
    "ErrorEvent",
    "EventNormalizer",
    "ExtensionError",
    "FinalTextEvent",
    "FrozenJsonMap",
    "HttpSseClient",
    "IsolatedEnvironment",
    "JsonRpcId",
    "JsonRpcProcessClient",
    "JsonlProcess",
    "LimitExceeded",
    "McpCallableBridge",
    "NormalizedEvent",
    "OptionalDependencyError",
    "PermissionDecision",
    "PermissionPolicy",
    "PermissionRequestEvent",
    "ProcessFailed",
    "ProviderReportedError",
    "ProtocolError",
    "ReasoningSummaryEvent",
    "SessionEvent",
    "SessionRef",
    "SseEvent",
    "TextDeduplicator",
    "TextDeltaEvent",
    "ToolCorrelator",
    "ToolProgressEvent",
    "ToolResultEvent",
    "ToolStartEvent",
    "TransportCancelled",
    "TransportError",
    "TransportLimits",
    "TransportTimeout",
    "UnsupportedPlatformError",
    "UsageEvent",
    "freeze_json",
    "map_permission_decision",
    "redact_diagnostics",
    "require_acp_sdk",
    "require_mcp_sdk",
    "validate_correlation_id",
]
